x-redis: &x-redis
  image: rediswarm/rediswarm:dev

x-deploy: &x-deploy-default
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  update_config:
    parallelism: 1
    delay: 10s
    failure_action: rollback
    monitor: 60s
    max_failure_ratio: 0.3
  rollback_config:
    parallelism: 1
    delay: 10s
    failure_action: pause
    monitor: 60s
    max_failure_ratio: 0.3

networks:
  rediswarm:

services:
  sentinel:
    <<: *x-redis
    hostname: sentinel-{{.Task.Slot}}
    environment:
      - REDISWARM_MODE=sentinel
      - REDISWARM_SLOT={{.Task.Slot}}
      - REDISWARM_SECRET=${REDISWARM_SECRET:-rediswarm}
      - REDIS_HOSTNAME_PREFIX=${REDIS_HOSTNAME_PREFIX:-replica-}
      - REDIS_SENTINEL_HOSTNAME_PREFIX=${REDIS_SENTINEL_HOSTNAME_PREFIX:-sentinel-}
    networks:
      - rediswarm
    deploy: 
      <<: *x-deploy-default
      replicas: 3

  replica:
    <<: *x-redis
    hostname: replica-{{.Task.Slot}}
    environment:
      - REDISWARM_MODE=redis
      - REDISWARM_SLOT={{.Task.Slot}}
      - REDISWARM_SECRET=${REDISWARM_SECRET:-rediswarm}
      - REDIS_HOSTNAME_PREFIX=${REDIS_HOSTNAME_PREFIX:-replica-}
      - REDIS_SENTINEL_ADDR=${REDIS_SENTINEL_ADDR:-sentinel}
    networks:
      - rediswarm
    deploy: 
      <<: *x-deploy-default
      replicas: 5
