name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master' # <- backward compatible for master branch
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master' # <- backward compatible for master branch
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub (${{ vars.DOCKERHUB_USERNAME }})
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            rediswarm/rediswarm
          tags: |
            type=ref,event=branch

      - name: Build and push
        uses: docker/bake-action@v3
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}
